INSERT INTO provinces (id, name) VALUES
    (2,'Albacete'),
    (3,'Alacant'),
    (4,'Almería'),
    (1,'Álava'),
    (33,'Asturias'),
    (5,'Ávila'),
    (6,'Badajoz'),
    (7,'Balears, Illes'),
    (8,'Barcelona'),
    (48,'Bizkaia'),
    (9,'Burgos'),
    (10,'Cáceres'),
    (11,'Cádiz'),
    (39,'Cantabria'),
    (12,'Castelló'),
    (51,'Ceuta'),
    (13,'Ciudad Real'),
    (14,'Córdoba'),
    (15,'A Coruña'),
    (16,'Cuenca'),
    (20,'Gipuzkoa'),
    (17,'Girona'),
    (18,'Granada'),
    (19,'Guadalajara'),
    (21,'Huelva'),
    (22,'Huesca'),
    (23,'Jaén'),
    (24,'León'),
    (27,'Lugo'),
    (25,'Lleida'),
    (28,'Madrid'),
    (29,'Málaga'),
    (52,'Melilla'),
    (30,'Murcia'),
    (31,'Navarra'),
    (32,'Ourense'),
    (34,'Palencia'),
    (35,'Las Palmas'),
    (36,'Pontevedra'),
    (26,'La Rioja'),
    (37,'Salamanca'),
    (38,'Santa Cruz de Tenerife'),
    (40,'Segovia'),
    (41,'Sevilla'),
    (42,'Soria'),
    (43,'Tarragona'),
    (44,'Teruel'),
    (45,'Toledo'),
    (46,'València'),
    (47,'Valladolid'),
    (49,'Zamora'),
    (50,'Zaragoza');

INSERT INTO locations (name, url, phone, latitude, longitude, province_id) VALUES
    ('Perrera Municipal de Bens',
     'http://www.coruna.es/adopcion',
     '+34981263093',
      43.3638, -8.4433, 15);

INSERT INTO origins (name, url) VALUES ('coruna.es','http://www.coruna.es/adopcion');
INSERT INTO origins (name, url) VALUES ('mundoanimalia.com','http://www.mundoanimalia.com/');

INSERT INTO `species` VALUES (1,'Perro',NULL),(2,'Gato',NULL);

INSERT INTO `races` (specie_id, name) VALUES 
    (1,'American Staffordshire terrier'),
    (1,'Can de palleiro'),
    (1,'Pastor alemán'),
    (1,'Pastor belga'),    
    (1,'Perro genérico'),
    (2,'Persa'),
    (2,'Siamés'),
    (2,'Gato genérico');
